### PR TITLE
Fixing Wrong type of memcopy argument

### LINKED ISSUE #16: Wrong type of memcopy argument
Hi,

I got this errors at compile time
```
/home/frederic/Arduino/libraries/SimpleFSM/src/SimpleFSM.cpp: In member function 'void SimpleFSM::add(Transition*, int)':
/home/frederic/Arduino/libraries/SimpleFSM/src/SimpleFSM.cpp:149:64: error: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'class Transition' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Werror=class-memaccess]
     memcpy(temp, transitions, num_standard * sizeof(Transition));
                                                                ^
In file included from /home/frederic/Arduino/libraries/SimpleFSM/src/SimpleFSM.h:14,
                 from /home/frederic/Arduino/libraries/SimpleFSM/src/SimpleFSM.cpp:2:
/home/frederic/Arduino/libraries/SimpleFSM/src/Transitions.h:46:7: note: 'class Transition' declared here
 class Transition : public AbstractTransition {
       ^~~~~~~~~~
/home/frederic/Arduino/libraries/SimpleFSM/src/SimpleFSM.cpp: In member function 'void SimpleFSM::add(TimedTransition*, int)':
/home/frederic/Arduino/libraries/SimpleFSM/src/SimpleFSM.cpp:189:60: error: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'class TimedTransition' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Werror=class-memaccess]
     memcpy(temp, timed, num_timed * sizeof(TimedTransition));
                                                            ^
In file included from /home/frederic/Arduino/libraries/SimpleFSM/src/SimpleFSM.h:14,
                 from /home/frederic/Arduino/libraries/SimpleFSM/src/SimpleFSM.cpp:2:
/home/frederic/Arduino/libraries/SimpleFSM/src/Transitions.h:64:7: note: 'class TimedTransition' declared here
 class TimedTransition : public AbstractTransition {
       ^~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
```

This is caused by the first argument of memcopy that should be cast to (void*)
Once corrected to this, no more errors
```
// line 149
    memcpy((void *)temp, transitions, num_standard * sizeof(Transition));

// line 189
    memcpy((void *)temp, timed, num_timed * sizeof(TimedTransition));

```

Regards,

### PR DESCRIPTION
**Pull request by joaopedrotaveira**
Fixes #16

### CODE REVIEW

**Review by LennartHennigs — APPROVED** [review]

**Comment by LennartHennigs** [comment]
Thank you @joaopedrotaveira,
Merged it. 
Will create a new release soon.

**Comment by ztaylor54** [comment]
@LennartHennigs Could you please create that release? I just see 1.3.0 in the registry and on GitHub.

Running into this issue, will add as a git dependency in the meantime to work around the release. Thanks!

**Comment by LennartHennigs** [comment]
Hey. Just releases it. 
Sorry, started doing some other changes and did not had time to finish them. 
Released this now as 1.3.1 other stuff will come later.

**Comment by ztaylor54** [comment]
Great, thank you! 🙏

**Comment by ztaylor54** [comment]
@LennartHennigs not sure exactly how pio registry works, but I still only see 1.3.0: https://registry.platformio.org/libraries/lennarthennigs/SimpleFSM

Do you need to update there as well?

**Comment by LennartHennigs** [comment]
Hey. Thank your pointing it out. 
Usually no. But I'll check and push it manually.

**Comment by LennartHennigs** [comment]
Published it now. Will check out GitHub actions now to out publish it. Thanks again for mentioning.

**Pull request merged**
